server:
  port: 4000
spring:
  application:
    name: ccctop-crowd-auth
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.200.128
    password:
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    app-code: 89eded7dc86f4e64a92b089a10e89e4a
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
    template-id: 908e94ccf08b4476ba6c876d13f084ad
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

